<?php

/**
 * @file
 * Miscellaneous hook implementations.
 */

/**
 * Implements hook_preprocess().
 */
function agile_newspaper_view_preprocess_islandora_newspaper(&$variables) {
  $years = element_children($variables['islandora_content_render_array']['tabs']);
  $variables['islandora_content_render_array']['controls']['#links'][0]['attributes']['onclick'] = 'Drupal.agile_newspaper_expand()';
  $images_added = agile_newspaper_view_add_images($years, $variables['islandora_content_render_array']['tabs']);
  $render_array = $variables['islandora_content_render_array']['tabs'][$years[0]];
  $render_array['#prefix'] = "<div id = 'current_year'>";
  $render_array['#suffix'] = "</div>";
  $form['year_selector'] = array(
    '#weight' => -1,
    '#id' => 'agile_year_select',
    '#type' => 'select',
    '#options' => $years,
    '#title' => t('Year of publication'),
  );
  $variables['islandora_content_render_array']['months'] = $render_array;
  $variables['islandora_content_render_array']['year_selector'] = $form['year_selector'];
  $path = drupal_get_path('module', 'agile_newspaper_view');
  drupal_add_js("$path/js/agile_newspaper.js");
  drupal_add_css("$path/css/agile_newspaper_view.css");
}

/**
 * Adds images to default issue output.
 *
 * @param array $years
 *  All represented years
 * @param array $input_array
 *   Existing rendered array
 */
function agile_newspaper_view_add_images($years, &$input_array) {
  foreach ($years as $year) {
    $current_year = $input_array[$year];
    $months = element_children($input_array[$year]);
    foreach ($months as $month) {
      $current_month = $current_year[$month];
      $issues = element_children($current_month);
      foreach ($issues as $issue) {
        $path = $current_month[$issue][0]['#path'];
        $input_array[$year][$month][$issue][0]['#prefix'] = '<span class = "agile_issue_title">';
        $input_array[$year][$month][$issue][0]['#suffix'] = '</span>';
        $input_array[$year][$month][$issue][] = agile_newspaper_view_make_element($path);
      }
    }
  }
}

/**
 * Makes image element
 *
 * @param string $path
 *   Path to islandora object
 * @return array
 *   Image element for render array
 */
function agile_newspaper_view_make_element($path) {
  return array(
    '#theme' => 'image',
    '#prefix' => '<span class = "agile_issue_image">',
    '#suffix' => '</span>',
    '#height' => '80px',
    '#path' => "",
    '#attributes' => array('class' => 'agile_newspaper_thumb','data' => "/$path/datastream/TN/view"),
    '#options' => array(
      'attributes' => array(),
      'html' => FALSE,
    ),
  );
}
